name: Lint & Test

on: push

jobs:
  lint:
    name: Lint and test python
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          bash scripts/install.fish

      - name: Run the linters
        run: |
          bash scripts/lint.fish

      - name: Run the tests
        run: |
          bash scripts/run-tests.fish
